name: .NET Console

on:
  push:
    branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: ActionPlays                         # Replace with your solution name, i.e. MyWpfApp.sln.
     # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    # Execute all unit tests in the solution
    # - name: Execute unit tests
    #   run: dotnet test

 

